using Mutagen.Bethesda;
using Mutagen.Bethesda.Synthesis;
using Mutagen.Bethesda.Skyrim;
using BSNoCustomMapMarkers;
using BSNoCustomMapMarkers.Parser;


namespace NoCustomMapMarkers
{
    public class Program
    {
        static Lazy<NoCustomMapMarkersSettings> Settings = null!;

        public static async Task<int> Main(string[] args)
        {
            return await SynthesisPipeline.Instance
                .AddPatch<ISkyrimMod, ISkyrimModGetter>(RunPatch)
                .SetAutogeneratedSettings(
                    nickname: "Settings",
                    path: "settings.json",
                    out Settings
                )
                .SetTypicalOpen(GameRelease.SkyrimSE, "BSNoCustomMapMarkers.esp")
                .Run(args);
        }

        public static void RunPatch(IPatcherState<ISkyrimMod, ISkyrimModGetter> state)
        {
            Console.WriteLine(">>>Patch Beyond Skyrim - No Custom MapMarkers");

            int counter = 0;

            var parser = SpreatsheetParserFactory.GetParser(Settings.Value);
            var importedMapMarkerData = parser.ParseDocument();

            var mapMarkerFormKey = Mutagen.Bethesda.FormKeys.SkyrimSE.Skyrim.Static.MapMarker.FormKey;
            var placedMapMarkers = state.LoadOrder.PriorityOrder.PlacedObject()
                .WinningContextOverrides(state.LinkCache)
                .Where(p  => p.Record.Base.FormKey == mapMarkerFormKey);
            
            foreach(var mapMarker in placedMapMarkers)
            {
                if (mapMarker.Record.MapMarker == null)
                    continue;

                if ((int)mapMarker.Record.MapMarker.Type < 60) //Marker is a vanilla marker
                    continue;

                IPlacedObject copiedMapMarker = mapMarker.GetOrAddAsOverride(state.PatchMod);

                if (copiedMapMarker.MapMarker == null)
                    continue;

                var mapMarkerData = importedMapMarkerData.Where(m => m.TNAM == (int)copiedMapMarker.MapMarker.Type).FirstOrDefault();
                if (mapMarkerData != null && mapMarkerData.NonCustomMarker != null)
                {
                    copiedMapMarker.MapMarker.Type = (MapMarker.MarkerType)mapMarkerData.NonCustomMarker.TNAM;
                }
                else
                {
                    copiedMapMarker.MapMarker.Type = MapMarker.MarkerType.Landmark;
                }

                //TODO  generate CoMAP file

                counter++;
            }

            Console.WriteLine($"Processed {counter} map markers");

            //TODO Export CoMAP file
        }
    }
}
