using Mutagen.Bethesda;
using Mutagen.Bethesda.Synthesis;
using Mutagen.Bethesda.Skyrim;
using BSNoCustomMapMarkers.Parser;
using BSNoCustomMapMarkers.Model;
using System.Reflection;


namespace BSNoCustomMapMarkers
{
    public class Program
    {
        static Lazy<NoCustomMapMarkersSettings> Settings = null!;

        public static async Task<int> Main(string[] args)
        {
            return await SynthesisPipeline.Instance
                .AddPatch<ISkyrimMod, ISkyrimModGetter>(RunPatch)
                .SetAutogeneratedSettings(
                    nickname: "Settings",
                    path: "settings.json",
                    out Settings
                )
                .SetTypicalOpen(GameRelease.SkyrimSE, "BSNoCustomMapMarkers.esp")
                .Run(args);
        }

        public static void RunPatch(IPatcherState<ISkyrimMod, ISkyrimModGetter> state)
        {
            Console.WriteLine(">>>Patch Beyond Skyrim - No Custom MapMarkers");

            Console.WriteLine("\n Test path:    ");
            Console.Write(Assembly.GetExecutingAssembly().Location);
            Console.WriteLine("\n");

            int counter = 0;

            var parser = SpreatsheetParserFactory.GetParser(Settings.Value);
            var importedMapMarkerData = parser.ParseDocument();

            var mapMarkerFormKey = Mutagen.Bethesda.FormKeys.SkyrimSE.Skyrim.Static.MapMarker.FormKey;
            var placedMapMarkers = state.LoadOrder.PriorityOrder.PlacedObject()
                .WinningContextOverrides(state.LinkCache)
                .Where(p => p.Record.Base.FormKey == mapMarkerFormKey);

            List<CoMAPInfo> coMAPInfos = [];

            foreach (var mapMarker in placedMapMarkers)
            {
                if (mapMarker.Record.MapMarker == null)
                    continue;

                if ((int)mapMarker.Record.MapMarker.Type < 60) //Marker is a vanilla marker
                    continue;

                IPlacedObject copiedMapMarker = mapMarker.GetOrAddAsOverride(state.PatchMod);

                if (copiedMapMarker.MapMarker == null)
                    continue;

                var mapMarkerData = importedMapMarkerData.Where(m => m.TNAM == (int)copiedMapMarker.MapMarker.Type).FirstOrDefault();
                if (mapMarkerData is not null && mapMarkerData.NonCustomMarker is not null && mapMarker is not null)
                {
                    copiedMapMarker.MapMarker.Type = (MapMarker.MarkerType)mapMarkerData.NonCustomMarker.TNAM;

                    var markername = mapMarker.Record.MapMarker.Name;

                    if (markername != null)
                    {
                        coMAPInfos.Add(new CoMAPInfo()
                        {
                            Id = mapMarker.Record.FormKey.ID,
                            MarkerName = markername.String,
                            ModName = mapMarker.Record.FormKey.ModKey.FileName,
                            OriginalMarker = mapMarkerData.NonCustomMarkerName,
                            IconName = mapMarkerData.CoMAPIconName
                        });
                    }
                }
                else
                {
                    copiedMapMarker.MapMarker.Type = MapMarker.MarkerType.Landmark;
                }
                counter++;
            }
            Console.WriteLine($"Processed {counter} map markers");

            if (Settings.Value.GenerateCoMAPData)
            {
                CoMAPGenerator.CoMAPGenerator.WriteCoMapFile(state, coMAPInfos);
            }
        }
    }
}
